FROM node:18-alpine

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh curl

WORKDIR /app

COPY package.json /app/

RUN npm install

COPY . /app/

EXPOSE 3000

CMD [ "npm", "start" ]