version: '3.8'
services:
  skillshare-app:
    build:
      context: ../client
      dockerfile: ../deployment/DockerFile.dev.frontend
    container_name: skillshare-app
    restart: always
    ports:
      - 3000:3000
    env_file:
      - ../environment/.env.dev.frontend
    volumes:
      - ../environment/.env.dev.frontend:/app/src/environment/.env.dev.frontend
      - ../client/src:/app/src
      - /app/node_modules
    stdin_open: true
    tty: true

  skillshare_db:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - ../environment/.env.postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  skillshare_backend:
    build:
      context: ../server
      dockerfile: ../deployment/DockerFile.dev.backend
    container_name: skillshare-backend
    restart: always
    ports:
      - 4000:4000
    env_file:
      - ../environment/.env.dev.backend
    depends_on:
      - skillshare_db
    volumes:
      - ../server/src:/app/src/
      - /app/node_modules

volumes:
  db:
    driver: local
